sakura-analysis:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /data/warehouse.duckdb
      schema: main
      threads: 4
      extensions:
        - httpfs
        - aws
      settings:
        s3_region: "ap-northeast-1"
        s3_endpoint: "https://your-sakura-object-storage-endpoint"
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"

